# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5d18c9e618947906b08ad2db4b9700b167dcd009926a6953ed17c158149cec3e3b2151536ef61e2dc0017743f577c46b046cb0c16e761322063696b43cae861

test:
  secret_key_base: c6eaa01db621b23168a393d3cad2f2cf702026e90676675ed90b9ded3f9fe75815f34019c77962da59a23cd60985e3fbbf06b80616d4bf7dad99169e83484b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
